### ISSUE TITLE
exception occured when I try to open a crypt pdf.

### ISSUE THREAD

**Issue by wustwg** [doolieSoft/PdfPasswordRemover#4]
hi, when I user your code to remove pdf password, 
exception raised at getNumPages.If I don't encrypt it , it seems that I can't get getNumPages attribute.

File "/home/wg/PycharmProjects/webdriverTest/venv/lib/python3.9/site-packages/PyPDF2/pdf.py", line 1150, in getNumPages
    raise utils.PdfReadError("File has not been decrypted")
PyPDF2.utils.PdfReadError: File has not been decrypted

Does it work normal  on your computer now?

**Comment by doolieSoft** [comment]
Hello, have you a pdf file to test?
Thanks

**Comment by doolieSoft** [comment]
Thanks bosek for your pull request.
