### ISSUE TITLE
Exception occurred with creation of file

### ISSUE THREAD

**Issue by ZaleJ** [doolieSoft/PdfPasswordRemover#5]
jizhaolun@Jis-MacBook-Pro ~ % sudo python3 /Users/jizhaolun/Documents/PdfPasswordRemover.py /Users/jizhaolun/Documents/test\ crack/ /Users/jizhaolun/Documents/test\ crack/
Password:
--- Exception occurred with creation of file /Users/jizhaolun/Documents/test crack/20210819142953_new/answer1.pdf ---
2 file(s) have been moved in /Users/jizhaolun/Documents/test crack/20210819142953_backup
0 pdf file(s) have been treated.
Press enter to continue...

**Comment by doolieSoft** [comment]
On my computer it is working fine.

**Comment by doolieSoft** [comment]
Thanks bosek for your pull request.
